export const professionalFields = [
  "Marketing / Communication",
  "Finance / Accounting",
  "Human Resources",
  "IT / Development",
  "Data / Analytics",
  "Sales / Business Development",
  "Logistics / Supply Chain",
  "Engineering",
  "Design / Creative",
  "Administration",
  "Education / Training",
  "Customer Service",
  "Other",
] as const;

export const cvLanguageOptions = ["Arabic", "French", "English"] as const;

export const commonToolsByField: Record<string, string[]> = {
  "Marketing / Communication": [
    "Meta Ads Manager",
    "Google Ads",
    "Google Analytics / GA4",
    "Google Search Console",
    "Canva",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe Premiere Pro",
    "CapCut",
    "Microsoft Excel",
    "PowerPoint",
    "Google Sheets",
    "HubSpot",
    "Mailchimp",
    "Hootsuite",
    "Buffer",
    "Notion",
    "WordPress",
    "Other",
  ],
  "Finance / Accounting": [
    "Microsoft Word",
    "Excel",
    "PowerPoint",
    "Outlook",
    "SAP",
    "Sage",
    "Odoo",
    "QuickBooks",
    "Power BI",
    "Other",
  ],
  "IT / Development": [
    "Git",
    "GitHub",
    "VS Code",
    "Docker",
    "SQL",
    "Postman",
    "Jira",
    "Python",
    "Microsoft Word",
    "Excel",
    "Outlook",
    "Other",
  ],
  Engineering: [
    "AutoCAD",
    "Revit",
    "SolidWorks",
    "CATIA",
    "MS Project",
    "Primavera P6",
    "Excel",
    "Outlook",
    "Other",
  ],
  "Design / Creative": [
    "Photoshop",
    "Illustrator",
    "InDesign",
    "Premiere Pro",
    "After Effects",
    "Figma",
    "Canva",
    "Microsoft Word",
    "PowerPoint",
    "Other",
  ],
  "Sales / Business Development": [
    "Salesforce",
    "HubSpot",
    "Zoho CRM",
    "Microsoft Excel",
    "Outlook",
    "PowerPoint",
    "Other",
  ],
  "Data / Analytics": [
    "Excel",
    "SQL",
    "Python",
    "Power BI",
    "Tableau",
    "Looker Studio",
    "Outlook",
    "Other",
  ],
  "Human Resources": [
    "Microsoft Word",
    "Excel",
    "PowerPoint",
    "Outlook",
    "Google Docs",
    "Teams",
    "Other",
  ],
  "Logistics / Supply Chain": [
    "Excel",
    "Outlook",
    "SAP",
    "Power BI",
    "Microsoft Word",
    "Other",
  ],
  Administration: [
    "Microsoft Word",
    "Excel",
    "PowerPoint",
    "Outlook",
    "Google Docs",
    "Google Drive",
    "Microsoft Teams",
    "Other",
  ],
  "Education / Training": [
    "Microsoft Word",
    "PowerPoint",
    "Outlook",
    "Google Docs",
    "Canva",
    "Other",
  ],
  "Customer Service": [
    "Microsoft Word",
    "Excel",
    "Outlook",
    "Microsoft Teams",
    "Zendesk",
    "Other",
  ],
  Other: [
    "Microsoft Word",
    "Excel",
    "PowerPoint",
    "Outlook",
    "Google Docs",
    "Google Drive",
    "Other",
  ],
};

export const professionalEvidenceByField: Record<string, string[]> = {
  "Marketing / Communication": [
    "Social Media Management", "Content Creation", "Content Strategy", "Digital Marketing Strategy",
    "Community Management", "Paid Advertising", "Meta Ads", "Google Ads", "Lead Generation",
    "Campaign Optimization", "Performance Reporting", "Analytics", "Market Research", "SEO",
    "Email Marketing", "CRM", "Influencer Marketing", "Event Marketing", "E-commerce",
    "Brand Management", "Copywriting", "Video Content", "Graphic Design", "Other",
  ],
  Other: ["Other"],
};

export const platformsByField: Record<string, string[]> = {
  "Marketing / Communication": [
    "Facebook", "Instagram", "TikTok", "LinkedIn", "X / Twitter", "Snapchat", "YouTube",
    "Pinterest", "Google", "Website / CMS", "Other",
  ],
};

export const collaborationTypesByField: Record<string, string[]> = {
  "Marketing / Communication": [
    "Internal teams", "Creative teams", "Sales teams", "Technical teams", "Agencies", "Freelancers",
    "Influencers / Content Creators", "Vendors / Suppliers", "Production teams", "Clients", "Other",
  ],
};

export const languageLevels = ["Native", "Fluent", "Professional", "Intermediate", "Basic", "Other"] as const;

export const designPreferences = [
  "ATS-friendly simple professional design",
  "I have a specific template",
  "Choose the most suitable design for me",
  "Other",
] as const;
